// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Hold `asset` open as a bin, answering the header and the rows at depth zero.
	 * 
	 *  With no `entry`, the rows are one per object. With one, `0x` and eight hex digits,
	 *  the rows are that object's properties and the answer carries its header facts.
	 */
	binOpen: (asset: AssetRef, entry: string | null) => __TAURI_INVOKE<({ ok: true; value: BinDocumentHandle }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("bin_open", { asset, entry }),
	/**
	 *  The rows under one node of an open document, `offset` in and at most `limit` of them.
	 * 
	 *  `entry` is the object's hash as `0x` and eight hex digits. `path` is the wire form
	 *  of the property path, empty for the object itself. Every row carries what the meta
	 *  schema declares for its field at the install's build.
	 */
	binChildren: (document: BinDocumentId, entry: string, path: string, offset: number, limit: number) => __TAURI_INVOKE<({ ok: true; value: BinRows }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("bin_children", { document, entry, path, offset, limit }),
	/**
	 *  The rows under each of several nodes of an open document, in the order asked.
	 * 
	 *  The projected read of "The projected read" in docs/ux/BIN_EDITOR.md, which a class
	 *  layout and a value row use in place of one [`bin_children`] call per node. Each path
	 *  answers one page, a path reaching nothing answers an empty one, and a call past the
	 *  row cap is refused so the caller batches.
	 */
	binRead: (document: BinDocumentId, entry: string, paths: string[]) => __TAURI_INVOKE<({ ok: true; value: BinRows[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("bin_read", { document, entry, paths }),
	/**  Drop one id. Its asset leaves the store with its last id. */
	binClose: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("bin_close", { document }),
	/**
	 *  One class's fields and their declared kinds at the install's build.
	 * 
	 *  Read out of the meta schema. `None` for a class the schema does not describe.
	 *  `class_hash` is `0x` and eight hex digits.
	 */
	classSchema: (classHash: string) => __TAURI_INVOKE<({ ok: true; value: ClassSchema | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("class_schema", { classHash }),
	runDiagnostics: () => __TAURI_INVOKE<({ ok: true; value: DiagnosticReport_Serialize }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("run_diagnostics"),
	/**
	 *  Launch an elevated PowerShell window so the user can run a fix command.
	 * 
	 *  On click of a "Run as administrator" button in the diagnostics UI, the
	 *  frontend copies the command to the clipboard and then calls this command.
	 *  We `ShellExecuteW` PowerShell with the `runas` verb (UAC prompt), then
	 *  `-NoExit` so the window stays open. When `with_banner` is true a short
	 *  hint line is printed up front telling the user the command is on their
	 *  clipboard and they should paste (Ctrl+V or right-click) and press Enter.
	 * 
	 *  Why not auto-execute the command? Auto-running registry deletes from a
	 *  freshly-elevated PowerShell with no review step is a footgun — the user
	 *  should at least see the command they're about to execute. Paste-then-Enter
	 *  is one extra keystroke and gives them a chance to bail out.
	 */
	openElevatedTerminal: (withBanner: boolean) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("open_elevated_terminal", { withBanner }),
	/**  Every incident the store holds, newest first. */
	listIncidents: () => __TAURI_INVOKE<({ ok: true; value: Incident_Serialize[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("list_incidents"),
	/**  Marks an incident dismissed. The verdict line goes, and the row dims. */
	dismissIncident: (id: string) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("dismiss_incident", { id }),
	/**  Marks every undismissed incident dismissed, and answers the ids it touched. */
	dismissAllIncidents: () => __TAURI_INVOKE<({ ok: true; value: string[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("dismiss_all_incidents"),
	/**  Reveals the incident's game log in the file manager. */
	revealGameLog: (id: string) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("reveal_game_log", { id }),
	/**
	 *  The incident as the text a support thread wants, with its token on the
	 *  second line. `hints` are the verdict's hints as the catalog renders them.
	 */
	incidentReport: (id: string, hints: string[]) => __TAURI_INVOKE<({ ok: true; value: string }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("incident_report", { id, hints }),
	/**  The incident folded into one short string, for a URL or a chat. */
	incidentToken: (id: string) => __TAURI_INVOKE<({ ok: true; value: string }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("incident_token", { id }),
	/**
	 *  Reads a token back, from the token alone or from a pasted report or URL
	 *  that carries one, against this build's tables.
	 */
	decodeIncidentToken: (token: string) => __TAURI_INVOKE<({ ok: true; value: DecodedIncident }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("decode_incident_token", { token }),
	/**
	 *  The pseudonym today's diagnostics would travel under, if any would.
	 * 
	 *  Answers `None` when nothing is collected, so the Privacy card can say that
	 *  rather than show an identity that reaches no one.
	 */
	telemetryIdentity: () => __TAURI_INVOKE<({ ok: true; value: string | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("telemetry_identity"),
	/**
	 *  Mint a new diagnostics secret, breaking the link to everything sent before.
	 * 
	 *  Takes effect at once rather than at the next midnight, because a reader who
	 *  presses it is asking for the link to break now. Answers the new pseudonym.
	 */
	resetTelemetrySecret: () => __TAURI_INVOKE<({ ok: true; value: string | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("reset_telemetry_secret"),
	/**
	 *  Report a crash the frontend caught, which is its only route to the wire.
	 * 
	 *  The frontend does not reach the network, so a boundary, a window error and a
	 *  rejection all come here and are queued on the one egress path.
	 */
	trackUiError: (error: UiError) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("track_ui_error", { error }),
	/**
	 *  The install the client's League session runs from, against the one the
	 *  manager is set up for.
	 * 
	 *  `None` when they agree, when no client or session answers, or when the
	 *  registry does not know the configured path. Read-only against the client.
	 */
	checkInstallMismatch: () => __TAURI_INVOKE<({ ok: true; value: InstallMismatch | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("check_install_mismatch"),
	/**
	 *  Points the manager at `install_root`, and puts the patcher session back up
	 *  on an overlay built from it.
	 * 
	 *  A running session is stopped, the path is saved the way Settings saves it,
	 *  and the session starts again with the config it ran with and a forced
	 *  rebuild. Without a running session the overlay is rebuilt and left for the
	 *  next start.
	 */
	switchLeagueInstall: (installRoot: string) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("switch_league_install", { installRoot }),
	/**  Create a new online room on the authoritative room server. */
	createRemoteRoom: (roomId: string, password: string) => __TAURI_INVOKE<({ ok: true; value: JoinedRoom }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("create_remote_room", { roomId, password }),
	/**  Join an existing online room on the authoritative room server. */
	joinRemoteRoom: (roomId: string, password: string) => __TAURI_INVOKE<({ ok: true; value: JoinedRoom }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("join_remote_room", { roomId, password }),
	/**  Retrieve active members and synchronization state from the server. */
	getRemoteRoomMembers: (roomId: string) => __TAURI_INVOKE<({ ok: true; value: RemoteMemberInfo[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("get_remote_room_members", { roomId }),
	/**  Synchronize manifest and missing blobs from the authoritative server. */
	syncRemoteRoom: (roomId: string) => __TAURI_INVOKE<({ ok: true; value: RoomSyncSnapshot }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("sync_remote_room", { roomId }),
	/**
	 *  Create local draft state for a room code. This intentionally does not create a remote room;
	 *  server-side creation, password handling, and owner tokens arrive with the authoritative service.
	 */
	createRoomDraft: (roomId: string) => __TAURI_INVOKE<({ ok: true; value: JoinedRoom }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("create_room_draft", { roomId }),
	/**
	 *  Join local draft state for a room code. It has no network side effect and does not accept a
	 *  password or token, so neither can accidentally be logged or stored in renderer state.
	 */
	joinRoomDraft: (roomId: string) => __TAURI_INVOKE<({ ok: true; value: JoinedRoom }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("join_room_draft", { roomId }),
	/**  List local memberships and their last accepted revision. */
	listRoomMemberships: () => __TAURI_INVOKE<({ ok: true; value: JoinedRoom[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("list_room_memberships"),
	/**
	 *  Leave local room state. Imported library mods and profiles remain local; cache cleanup requires
	 *  the separate explicit prune command.
	 */
	leaveRoom: (roomId: string) => __TAURI_INVOKE<({ ok: true; value: boolean }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("leave_room", { roomId }),
	/**  Restore the durable snapshot for one room without making a network request. */
	getRoomSyncSnapshot: (roomId: string) => __TAURI_INVOKE<({ ok: true; value: RoomSyncSnapshot }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("get_room_sync_snapshot", { roomId }),
	/**
	 *  Submit one manifest from the isolated room transport.
	 * 
	 *  It stages, verifies, and atomically accepts only already-cached blobs. Missing blobs remain a
	 *  pending room transfer; no mod is installed, enabled, applied, or launched.
	 */
	synchronizeRoomManifest: (manifest: RoomManifest) => __TAURI_INVOKE<({ ok: true; value: RoomSyncSnapshot }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("synchronize_room_manifest", { manifest }),
	/**
	 *  Discard an incomplete target revision while retaining the last accepted revision and its cache
	 *  references.
	 */
	discardRoomTarget: (roomId: string) => __TAURI_INVOKE<({ ok: true; value: RoomSyncSnapshot }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("discard_room_target", { roomId }),
	/**  Read the complete accepted room manifest, if this machine has one. */
	getAcceptedRoomManifest: (roomId: string) => __TAURI_INVOKE<({ ok: true; value: RoomManifest | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("get_accepted_room_manifest", { roomId }),
	/**
	 *  Read durable local workflow facts for a room. This is informational only: a profile binding
	 *  does not select the profile, and neither preparation nor profile creation applies anything to
	 *  the game.
	 */
	getRoomLocalStatus: (roomId: string) => __TAURI_INVOKE<({ ok: true; value: RoomLocalStatus }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("get_room_local_status", { roomId }),
	/**  Report cache reference and pending-transfer counts without revealing local paths. */
	getRoomCacheStatus: () => __TAURI_INVOKE<({ ok: true; value: RoomCacheStatus }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("get_room_cache_status"),
	/**  Explicitly prune only unreferenced room-cache blobs. It cannot delete an installed library mod. */
	pruneRoomCache: () => __TAURI_INVOKE<({ ok: true; value: CachePruneReport }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("prune_room_cache"),
	/**
	 *  Explicitly import the accepted revision through the existing archive pipeline, registered
	 *  disabled. This command never selects a profile or starts the patcher.
	 */
	prepareRoomRevision: (roomId: string) => __TAURI_INVOKE<({ ok: true; value: RoomPreparationSummary }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("prepare_room_revision", { roomId }),
	/**
	 *  Explicitly create/update the non-active profile corresponding to an already prepared revision.
	 *  The existing profile switch and Start/Play commands remain separate user actions.
	 */
	createRoomProfile: (roomId: string) => __TAURI_INVOKE<({ ok: true; value: RoomProfileSummary }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("create_room_profile", { roomId }),
};

/* Types */
/**
 *  What went wrong, as the fields the frontend translates over.
 * 
 *  The frontend owns every sentence a user reads (ADR-0017), so no variant
 *  carries one. A `detail` is prose from outside the app, such as an OS or
 *  crate error, which the frontend draws as data under a title of its own.
 */
export type AppErrorResponse = 
/**  File system I/O failed. */
{ code: "IO"; detail: string } | 
/**  JSON could not be read or written. */
{ code: "SERIALIZATION"; detail: string } | 
/**  A `.modpkg` could not be processed. */
{ code: "MODPKG"; detail: string } | 
/**  No League of Legends installation is configured. */
{ code: "LEAGUE_NOT_FOUND" } | 
/**  A file or directory path cannot be used. */
{ code: "INVALID_PATH"; path: string } | 
/**  No installed mod has this id. */
{ code: "MOD_NOT_FOUND"; modId: string } | 
/**  Input failed validation. */
{ code: "VALIDATION_FAILED"; detail: string } | 
/**  Internal state was not what the operation needed. */
{ code: "INTERNAL_STATE"; detail: string } | 
/**  A failure with no code of its own. */
{ code: "UNKNOWN"; detail: string } | 
/**  No workshop directory is configured. */
{ code: "WORKSHOP_NOT_CONFIGURED" } | 
/**  No workshop project has this name. */
{ code: "PROJECT_NOT_FOUND"; projectName: string } | 
/**  A workshop project with this name already exists. */
{ code: "PROJECT_ALREADY_EXISTS"; projectName: string } | 
/**  A workshop project could not be packed. */
{ code: "PACK_FAILED"; detail: string } | 
/**  A `.fantome` could not be processed. */
{ code: "FANTOME"; detail: string } | 
/**  A WAD could not be read or built. */
{ code: "WAD"; detail: string } | 
/**
 *  The patcher refused or a start failed. The variant says which.
 * 
 *  One code, not one per [`PatcherError`] variant: the whole error travels,
 *  so a code per variant would put the same discriminant on the wire twice.
 */
{ code: "PATCHER"; error: PatcherError } | 
/**  A ZIP archive could not be processed. */
{ code: "ZIP"; detail: string } | 
/**  The library index was written by a newer app version. */
{ code: "SCHEMA_VERSION_TOO_NEW"; fileVersion: number; maxSupported: number } | 
/**  A workshop operation failed. The variant says which. */
{ code: "WORKSHOP"; error: WorkshopError } | 
/**  A launch failed. The variant says which and carries its remedy's inputs. */
{ code: "LAUNCHER"; error: LauncherError } | 
/**
 *  A hashtable cache operation failed.
 * 
 *  `HashtableError` is not `Serialize`, so the detail is where the
 *  variant's own words ride.
 */
{ code: "HASHTABLE"; detail: string } | 
/**  An asset could not be previewed. */
{ code: "PREVIEW"; detail: string } | 
/**  The bytes are not a bin the toolkit reads. */
{ code: "BIN_UNREADABLE"; detail: string } | 
/**  No open bin document has the id. A close and an eviction both remove one. */
{ code: "BIN_NOT_OPEN" } | 
/**  No node of the open bin has the address. */
{ code: "BIN_NODE_NOT_FOUND"; address: string } | 
/**  A projected read asked for more rows than one call answers. */
{ code: "BIN_READ_TOO_WIDE"; rows: number; cap: number } | 
/**
 *  An overlay build or analysis failed.
 * 
 *  One code with a category, not one per category: `ltk_overlay::Error`
 *  is `#[non_exhaustive]`, so a new category arrives as
 *  [`OverlayErrorCategory::Other`] rather than as a code the frontend has
 *  never heard of.
 */
{ code: "OVERLAY"; category: OverlayErrorCategory; detail: string } | 
/**  A download was asked for from a domain the trusted providers list omits. */
{ code: "UNTRUSTED_DOMAIN"; domain: string } | 
/**
 *  Something GitHub publishes could not be read. The kind says which
 *  remedy applies, and the feed says what was being read.
 */
{ code: "GITHUB"; feed: GitHubFeed; kind: GitHubErrorKind; detail: string } | 
/**
 *  A room synchronization operation failed. Raw room errors can contain local paths, so only
 *  this stable category reaches the webview.
 */
{ code: "ROOM_SYNC"; kind: RoomSyncErrorKind };

/**
 *  Where a previewed asset's bytes come from.
 * 
 *  A reference crosses IPC from the webview, so every path in one is untrusted.
 *  [`read`](Self::read) checks a relative path against the root it belongs to
 *  rather than joining it on, and [`File`](Self::File) is the one variant that
 *  names a path outright.
 */
export type AssetRef = 
/**  A file of one layer of a workshop project. */
{ kind: "layer"; 
/**  The project directory. */
project: string; layer: string; 
/**  Path relative to the layer root, with forward slashes. */
path: string } | 
/**  One chunk of one archive of the installed game. */
{ kind: "gameChunk"; 
/**  A `DATA/FINAL`-relative archive name. */
wad: string; 
/**  The chunk's path hash as 16 lowercase hex digits. */
pathHash: string } | 
/**
 *  Any file on disk, for a preview that belongs to no project.
 * 
 *  Confined to no root, because a file dropped on the window or picked
 *  from a dialog is anywhere. The built-in `asset:` protocol already serves
 *  the whole filesystem to the same webview, so this adds no reach.
 */
{ kind: "file"; path: string };

/**  Why a suspect is one, as the line under its name. */
export type Because = "holds-the-path" | "redirected" | "rejected" | "did-not-verify" | "skipped" | "could-not-mount" | 
/**  What an incident stored before the reason was written down reads as. */
"unknown";

/**
 *  What an open answers: the id, the header, and the rows at depth zero.
 * 
 *  A file open answers one row per object. An open with an entry answers that object's
 *  properties and its header facts (ADR-0028).
 */
export type BinDocumentHandle = {
	document: BinDocumentId,
	header: BinHeader,
	rows: BinRow[],
	/**  The object the open is over. Absent for a file open. */
	object: BinObjectHeader | null,
};

/**
 *  The id one open of a document is addressed by.
 * 
 *  An id is never reused within a process. A call carrying a closed id fails as
 *  [`BinDocumentError::NotOpen`] and reaches no other document.
 */
export type BinDocumentId = number;

/**  Which kind of bin file a document holds. */
export type BinFileKind = 
/**  A `PROP`: the objects themselves. */
"prop" | 
/**  A `PTCH`: a layer over another bin. */
"patch";

/**  What the header row says about an open bin. */
export type BinHeader = {
	kind: BinFileKind,
	/**  The file version of a `PROP`. A `PTCH` carries none. */
	version: number | null,
	/**  The objects the file declares. For a `PTCH`, the objects it adds. */
	objects: number,
	dependencies: string[],
	/**  The patch records of a `PTCH`. Nothing draws them. */
	patches: number,
	/**  The objects a `PTCH` deletes. */
	deleted: number,
};

/**  The facts an object tab's header draws. "The object tab" in docs/ux/BIN_EDITOR.md. */
export type BinObjectHeader = {
	/**  The object's path hash, `0x` and eight hex digits. */
	entry: string,
	/**  The object's path, or its hex where no table names it. */
	name: string,
	/**  The name is a hash no table names. */
	unnamed: boolean,
	/**  `0x` and eight hex digits. */
	classHash: string,
	/**  The class as the tables name it. Absent where no table does. */
	class: string | null,
	/**  How many properties the object holds. */
	properties: number,
};

/**  One row of the viewer, flat. */
export type BinRow = {
	/**  The object's path hash, `0x` and eight hex digits. */
	entry: string,
	/**  The property path on the wire, every field a hash. Empty for the object itself. */
	path: string,
	/**  The same path for a person. Empty for the object itself. */
	label: string,
	node: RowNode,
	/**  What the row is called: the object's path, the property's name, `[i]` or the key. */
	name: string,
	/**  The name is a hash no table names. */
	unnamed: boolean,
	/**  The value's kind. An object row has none. */
	kind: PropertyKind | null,
	value: BinValue,
	/**
	 *  What the schema declares for the field at the install's build. Absent for an
	 *  object, an element, an entry, and a field the schema has no line for.
	 */
	declared: DeclaredKind | null,
};

/**  A window of rows under one node, and how many there are in all. */
export type BinRows = {
	rows: BinRow[],
	total: number,
};

/**
 *  A row's value, in the shape its widget draws.
 * 
 *  A hash rides beside the name a table gave it. A person reads the name and a Copy
 *  takes the hash.
 */
export type BinValue = { type: "none" } | 
/**  A `Bool` or a `BitBool`. */
{ type: "bool"; value: boolean } | 
/**  Any integer kind, as text. A `U64` does not fit a JSON number. */
{ type: "integer"; text: string } | { type: "float"; value: number | null } | 
/**  Two, three or four components. */
{ type: "vector"; values: (number | null)[] } | 
/**  Sixteen cells, row-major. */
{ type: "matrix"; values: (number | null)[] } | { type: "color"; r: number; g: number; b: number; a: number } | { type: "string"; value: string } | 
/**  `0x` and eight hex digits, and the string behind it where a table names one. */
{ type: "hash"; hash: string; name: string | null } | 
/**  Sixteen hex digits, and the chunk's path where a table names one. */
{ type: "wadChunkLink"; hash: string; path: string | null } | 
/**  `0x` and eight hex digits, and the object's path where a table names one. */
{ type: "objectLink"; hash: string; name: string | null } | 
/**  A `Container` or an `UnorderedContainer`, and the kind of every item. */
{ type: "container"; len: number; itemKind: PropertyKind } | 
/**  A `Struct` with a class, or an `Embedded`. */
{ type: "struct"; classHash: string; class: string | null; len: number } | 
/**  A `Struct` with a class hash of zero. */
{ type: "null" } | 
/**  Whether a value is held, and the kind it is or would be. */
{ type: "optional"; present: boolean; itemKind: PropertyKind } | 
/**  The entries, and the kinds the map declares for its keys and its values. */
{ type: "map"; len: number; keyKind: PropertyKind; valueKind: PropertyKind } | 
/**  A leaf this build has no widget for. */
{ type: "undrawn" };

/**  Patcher binary identity */
export type BinaryId = {
	/**  16 hex sha-256 */
	hash: string,
	built: number | null,
};

export type CachePruneReport = {
	removedBlobs: number,
	reclaimedBytes: number,
};

/**  Coarse grouping for the UI. */
export type Category = 
/**  OS-level checks (Windows version, UAC, long paths). */
"system" | 
/**  League installation checks (path, writability, compat flags). */
"league" | 
/**  LTK Manager checks (admin status, install path). */
"manager" | 
/**  Patcher / DLL checks (presence, signature, locked-by handles). */
"patcher" | 
/**  Storage / mod-storage path checks. */
"storage" | 
/**  Mod library state checks (index integrity). */
"library";

/**  Result of a single diagnostic check. */
export type Check = Check_Serialize | Check_Deserialize;

/**  A single key/value detail row attached to a check. */
export type CheckDetail = {
	key: string,
	value: string,
};

/**  Result of a single diagnostic check. */
export type Check_Deserialize = {
	/**  Stable identifier (e.g. `"windows.long_paths"`). Survives label changes. */
	id: string,
	/**  Human-readable label. */
	label: string,
	category: Category,
	severity: Severity,
	/**  One-line summary of the result, shown next to the label. */
	summary: string,
	/**  Optional structured details, shown when the row is expanded. */
	details?: CheckDetail[],
	/**  Optional plain-text guidance for the user. */
	suggestion?: string | null,
	/**
	 *  Optional command (PowerShell / cmd / shell) to run as a fix. Shown
	 *  alongside the suggestion with a copy button.
	 */
	fixCommand?: string | null,
};

/**  Result of a single diagnostic check. */
export type Check_Serialize = {
	/**  Stable identifier (e.g. `"windows.long_paths"`). Survives label changes. */
	id: string,
	/**  Human-readable label. */
	label: string,
	category: Category,
	severity: Severity,
	/**  One-line summary of the result, shown next to the label. */
	summary: string,
	/**  Optional structured details, shown when the row is expanded. */
	details: CheckDetail[],
	/**  Optional plain-text guidance for the user. */
	suggestion?: string | null,
	/**
	 *  Optional command (PowerShell / cmd / shell) to run as a fix. Shown
	 *  alongside the suggestion with a copy button.
	 */
	fixCommand?: string | null,
};

/**  One class as the class card draws it: its name, and its fields typed at one build. */
export type ClassSchema = {
	/**  The class as the database names it. */
	name: string | null,
	/**
	 *  The content build `declared` is read at: the install's, or the newest the
	 *  database names where the install has none it describes.
	 */
	build: number,
	/**
	 *  The patch a player names, where the install's own build is what was read.
	 * 
	 *  Absent where the database describes no build the install has and the newest it
	 *  names stood in, because that build belongs to no patch this install knows.
	 */
	patch: string | null,
	/**  The named fields first, by name, and the unnamed after them by hash. */
	fields: FieldSchema[],
};

/**
 *  What a verdict cost the player, which is a fact whatever the manager makes
 *  of the line that reported it.
 * 
 *  The axis that replaced a confidence word. How firmly a log code can be read
 *  is a claim about the manager's own table and belongs to the sentence that
 *  reads the code, not stamped over what happened to the game.
 * 
 *  Ordered by how much the game lost, worst last.
 */
export type Consequence = 
/**  The overlay served the game without one archive, and the rest applied. */
"archive-dropped" | 
/**  No mod reached the game. */
"overlay-off" | 
/**  The game stopped making progress and never reached play. */
"game-hung" | 
/**  The game did not survive. */
"game-stopped";

/**  SHA-256 rendered as exactly 64 lowercase hexadecimal characters. */
export type ContentHash = string;

/**  What the schema declares for a field, beside whether the file's kind is that. */
export type DeclaredKind = {
	shape: KindShape,
	/**
	 *  The file's kind is not the declared one, as the Problems rule for a property
	 *  type reads the two.
	 */
	mismatch: boolean,
};

/**
 *  One patcher binary as a decoded token presents it: the checksum, and the
 *  build date as a full timestamp.
 */
export type DecodedBinary = {
	hash: string,
	/**  RFC 3339, UTC, when the build date was a date. */
	built: string | null,
};

/**
 *  A token read against this build's tables, for a reader.
 * 
 *  Each enum is `None` for a number this build does not know, with the
 *  verdict's number kept beside it, so a token from a newer manager reads as
 *  far as it can and never as an error.
 */
export type DecodedIncident = {
	/**  RFC 3339, UTC, to the minute, or `None` when the token carried no time. */
	endedAt: string | null,
	/**  `1.14.0`. */
	manager: string,
	/**  `16.16.804.9184`. */
	game: string | null,
	verdict: VerdictKind | null,
	/**
	 *  The verdict's number as the token carries it, for one this build does
	 *  not know.
	 */
	verdictCode: number,
	/**  The verdict's title, or `Verdict 17` for one this build does not know. */
	title: string,
	consequence: Consequence | null,
	origin: OriginKind | null,
	overlay: OverlayOutcome | null,
	scan: ScanMode | null,
	launch: LaunchKind | null,
	injected: boolean,
	hostElevated: boolean,
	phase: GamePhase | null,
	ending: Ending,
	durationSecs: number | null,
	/**  Each code with what this build's table says about it. */
	codes: EvidenceCode[],
	lastLoadStep: number | null,
	missingHash: string | null,
	subject: string | null,
	suspects: string[],
	skipped: SkippedArchive[],
	redirectedCount: number,
	enabledCount: number,
	/**  The hook DLL that ran, with its build date read out. */
	dll: DecodedBinary | null,
	/**  The injection host that ran. */
	host: DecodedBinary | null,
	/**  Whether both binaries are the ones the sender's manager build shipped. */
	patcherOk: boolean | null,
	scanStatus: ScanStatus | null,
	/**  The status code as the scan reported it, beside the reading. */
	scanStatusCode: string | null,
	failure: string | null,
	overlayDetail: string | null,
};

/**  Full diagnostic report returned by `run_diagnostics`. */
export type DiagnosticReport = DiagnosticReport_Serialize | DiagnosticReport_Deserialize;

/**  Full diagnostic report returned by `run_diagnostics`. */
export type DiagnosticReport_Deserialize = {
	/**  ISO-8601 UTC timestamp. */
	generatedAt: string,
	/**  Manager version (matches `Cargo.toml`). */
	appVersion: string,
	/**  All checks in display order. */
	checks: Check_Deserialize[],
};

/**  Full diagnostic report returned by `run_diagnostics`. */
export type DiagnosticReport_Serialize = {
	/**  ISO-8601 UTC timestamp. */
	generatedAt: string,
	/**  Manager version (matches `Cargo.toml`). */
	appVersion: string,
	/**  All checks in display order. */
	checks: Check_Serialize[],
};

/**  How the game ended, as far as anything said. */
export type Ending = {
	/**
	 *  The Riot Client's reason: `Exit`, `Interrupt`, `Timeout`, `Unknown`, or a
	 *  spelling the crate does not know. `None` on the Classic launch flow.
	 */
	exitReason: string | null,
	exitCode: number | null,
	/**
	 *  Whether `last_crash` fell inside the game's window. `None` when the
	 *  marker was not read.
	 */
	crashed: boolean | null,
};

/**
 *  Which [`AppError`] a failure was, as a name that outlives its message.
 * 
 *  A message is for a reader and can be empty. This is the part a consumer
 *  switches on, so it survives being recorded, stored and read back long after
 *  the error value is gone. The Tauri shell maps it to its own `ErrorCode`, and
 *  a CLI could map the same names to exit codes.
 */
export type ErrorKind = "IO" | "SERIALIZATION" | "MODPKG" | "LEAGUE_NOT_FOUND" | "INVALID_PATH" | "MOD_NOT_FOUND" | "VALIDATION_FAILED" | "INTERNAL_STATE" | "OTHER" | "WORKSHOP_NOT_CONFIGURED" | "PROJECT_NOT_FOUND" | "PROJECT_ALREADY_EXISTS" | "PACK_FAILED" | "FANTOME" | "WAD_ERROR" | "WAD_BUILDER_ERROR" | "PATCHER" | "LAUNCHER" | "ZIP_ERROR" | "SCHEMA_VERSION_TOO_NEW" | "WORKSHOP" | "HASHTABLE" | "PREVIEW" | "BIN_DOCUMENT" | "OVERLAY" | "UNTRUSTED_DOMAIN";

/**  One line the verdict rests on. */
export type Evidence = {
	/**  Seconds into the game where the source has one, else the wall clock. */
	at: string,
	source: EvidenceSource,
	line: string,
	/**  The lines under a game record with no columns of their own. */
	detail?: string[],
	code: EvidenceCode | null,
};

/**  What the table says about a code on an evidence line. */
export type EvidenceCode = {
	id: string,
	/**  The kind column, or `None` when the table has no row. */
	kind: string | null,
	meaning: string | null,
	mark: EvidenceMark | null,
};

/**
 *  How firm a row's reading is, which is a claim about this table and no more.
 * 
 *  It hedges the one sentence that reads the code and nothing else. What a
 *  verdict cost the game is a fact the manager observed, so the mark never
 *  grades it - see [`Consequence`](super::incident::Consequence).
 */
export type EvidenceMark = 
/**  The reading is a fact, and the sentence states it as one. */
"confirmed" | 
/**  The reading is probable, and the sentence says `probably`. */
"inferred";

/**  Where a line of evidence came from. */
export type EvidenceSource = "patcher" | "host" | "dll" | "game" | "client";

/**  One field's type over one span of builds. */
export type FieldRevision = {
	/**  The first content build the revision holds for. */
	from: number,
	/**  The last content build it holds for, inclusive. Open where absent. */
	to: number | null,
	/**  Absent for a type this build cannot map. */
	shape: KindShape | null,
};

/**  One field of a class: its name, its type at the card's build, and every revision. */
export type FieldSchema = {
	/**  `0x` and eight hex digits. */
	hash: string,
	/**  The field as the database names it. */
	name: string | null,
	/**
	 *  The type at the card's build. Absent where no revision covers the build, and
	 *  where the revision names a type this build cannot map.
	 */
	declared: KindShape | null,
	/**  Oldest first. */
	revisions: FieldRevision[],
};

/**  The facts the game log gives about the game itself. */
export type GameInfo = {
	version: string,
	contentVersion: string,
	logPath: string,
	/**  The install root the game ran from, as its command line named it. */
	gameBaseDir: string | null,
};

/**  How far the game got, as its log says. */
export type GamePhase = 
/**  No log was read. */
"unknown" | 
/**  The loading screen never finished. */
"loading" | 
/**  `Loading Ended` was written. */
"in-game" | 
/**  The game ended the way it should. */
"torn-down";

/**  Which way a read of GitHub failed, as the remedy it has. */
export type GitHubErrorKind = 
/**  GitHub was never reached. Waiting for a connection is the remedy. */
"OFFLINE" | 
/**  The address has spent its unauthenticated quota. Waiting is the remedy. */
"RATE_LIMITED" | 
/**  The request went out and what came back is not what was asked for. */
"HTTP";

/**  Which of the things GitHub publishes a read was after. */
export type GitHubFeed = "RELEASES" | "ANNOUNCEMENTS" | "NOTICES";

/**
 *  A setting or an action the evidence points at, under the verdict.
 * 
 *  A code on the wire and in the store. The frontend catalog owns the sentence
 *  (ADR-0017), and the report text takes the sentences from there.
 */
export type Hint = "system-checks" | "update-manager" | "rebuild-overlay" | "check-game-path" | "texture-dimensions" | "repair-install" | "update-driver" | "free-memory" | "open-project" | "start-first" | "scan-up-front" | "copy-report" | "disable-suspect" | "remove-skinhack" | "reimport-mod" | "repair-game" | "elevate" | "signature" | 
/**
 *  A modded archive was in the game, and a texture far larger than what it
 *  replaces raises the odds of an allocation failing.
 */
"large-textures";

/**  The record the manager keeps for one game that went wrong. */
export type Incident = Incident_Serialize | Incident_Deserialize;

/**  The record the manager keeps for one game that went wrong. */
export type Incident_Deserialize = {
	/**  The game log's stamp, or the game's start when there is no log. */
	id: string,
	/**  RFC 3339, UTC. */
	startedAt: string,
	endedAt: string,
	/**  Library, or the workshop projects under test. */
	origin: SessionOrigin,
	/**  Whether the DLL attached to this game. */
	injected: boolean,
	hostElevated?: boolean,
	patcher?: PatcherBinaries_Deserialize,
	overlay: OverlayOutcome,
	overlayDetail?: string | null,
	redirected: string[],
	skipped: SkippedArchive[],
	enabledCount?: number,
	launch: LaunchKind,
	scan: ScanMode | null,
	scanStatus: ScanStatus | null,
	/**
	 *  The token the scan reported, beside [`Incident::scan_status`]'s reading
	 *  of it. The only part of a rejection a reader cannot get from the status.
	 */
	scanStatusCode?: string | null,
	/**
	 *  How many archives the scan rejected. The verdict names the first, so
	 *  the rest is what a reader still has to be told about.
	 */
	scanRejected?: number,
	phase?: GamePhase,
	game: GameInfo | null,
	ending: Ending,
	/**  Set when the session failed before any game, which is the whole story. */
	failure?: SessionFailure | null,
	verdict: Verdict_Deserialize,
	evidence: Evidence[],
	suspects: Suspect[],
	/**  The user has seen it and closed the line. */
	dismissed: boolean,
};

/**  The record the manager keeps for one game that went wrong. */
export type Incident_Serialize = {
	/**  The game log's stamp, or the game's start when there is no log. */
	id: string,
	/**  RFC 3339, UTC. */
	startedAt: string,
	endedAt: string,
	/**  Library, or the workshop projects under test. */
	origin: SessionOrigin,
	/**  Whether the DLL attached to this game. */
	injected: boolean,
	hostElevated: boolean,
	patcher: PatcherBinaries_Serialize,
	overlay: OverlayOutcome,
	overlayDetail: string | null,
	redirected: string[],
	skipped: SkippedArchive[],
	enabledCount: number,
	launch: LaunchKind,
	scan: ScanMode | null,
	scanStatus: ScanStatus | null,
	/**
	 *  The token the scan reported, beside [`Incident::scan_status`]'s reading
	 *  of it. The only part of a rejection a reader cannot get from the status.
	 */
	scanStatusCode: string | null,
	/**
	 *  How many archives the scan rejected. The verdict names the first, so
	 *  the rest is what a reader still has to be told about.
	 */
	scanRejected: number,
	phase: GamePhase,
	game: GameInfo | null,
	ending: Ending,
	/**  Set when the session failed before any game, which is the whole story. */
	failure: SessionFailure | null,
	verdict: Verdict_Serialize,
	evidence: Evidence[],
	suspects: Suspect[],
	/**  The user has seen it and closed the line. */
	dismissed: boolean,
};

/**  Which stage of a start failed, for [`PatcherError::InjectionFailed`]. */
export type InjectionStage = 
/**
 *  The host process never came up - it could not be spawned, configured, or
 *  told to start. Antivirus, a missing binary or a declined UAC prompt are
 *  the usual causes, so diagnostics are the useful response.
 */
"HOST" | 
/**  The host ran, but the game was never patched. */
"INJECTION";

/**
 *  The install the manager is set up for, against the one the client's League
 *  session runs from.
 */
export type InstallMismatch = {
	/**  The install root the manager is set up for. */
	configuredPath: string,
	/**  The patchline the registry lists that root under. */
	configuredPatchline: string,
	/**  The patchline of the League session the client has open. */
	sessionPatchline: string,
	/**  That patchline's install root. */
	sessionPath: string,
};

export type JoinedRoom = {
	roomId: string,
	memberId: string,
	lastAcceptedRevision: number,
	joinedAtMs: number,
	updatedAtMs: number,
};

/**
 *  A type as the tag composes it: the kind, a `Map`'s key, and what a container holds.
 * 
 *  The wire form of [`Shape`]. A row's tag and a card's field draw it as `list[embed]`
 *  or `map[hash,string]`.
 */
export type KindShape = {
	kind: PropertyKind,
	/**  A `Map`'s key kind. */
	key: PropertyKind | null,
	/**  What an `Option`, a list or a `Map` holds. */
	value: PropertyKind | null,
};

/**  What kind of game it was, as the DLL read the command line. */
export type LaunchKind = "match" | "replay" | "spectator" | "pbe";

/**
 *  Why a launch request could not be delivered.
 * 
 *  Each variant has a different remedy ("set your game path", "open the Riot
 *  Client"), so each gets its own `ErrorCode` in the shell rather than sharing
 *  one with a discriminating field.
 */
export type LauncherError = 
/**
 *  No `RiotClientInstalls.json`, or nothing in it resolves to an exe on
 *  disk.
 */
{ kind: "RIOT_CLIENT_NOT_FOUND"; installsPath: string } | 
/**
 *  A client is alive and holding the lockfile, but never answered that it
 *  took the launch args. Cold-starting over it would terminate the user's
 *  session, so this is terminal.
 */
{ kind: "RIOT_CLIENT_UNREACHABLE"; reason: string } | 
/**
 *  The client understood the request and refused it - the Terms of Service
 *  are unaccepted, the game is out of date, the patchline is locked. The
 *  remedy is always something the player does in the Riot Client itself,
 *  and `riot_error_code` is Riot's own machine-readable tag for which one.
 */
{ kind: "REFUSED"; riotErrorCode: string; message: string } | 
/**
 *  The user called the launch off while it was waiting.
 * 
 *  Nothing failed, so nothing may be shown as a failure - a toast saying
 *  the launch broke, behind a Cancel button the user just pressed, is the
 *  one outcome this variant exists to prevent. Stopping abandons the wait
 *  and not the launch: a request the client already accepted still starts
 *  a game.
 */
{ kind: "STOPPED" } | 
/**
 *  The launcher was built with something it cannot use. A bug here rather
 *  than a condition the user can clear.
 */
{ kind: "MISCONFIGURED"; reason: string } | 
/**  `RiotClientServices.exe` could not be spawned. */
{ kind: "SPAWN_FAILED"; reason: string } | { kind: "UNSUPPORTED_PLATFORM" } | 
/**
 *  A failure this build of the manager does not know, from a newer
 *  [`ritoclient`], carrying that error's own prose.
 */
{ kind: "OTHER"; message: string };

/**  What the session was started for, without the paths a workshop one carries. */
export type OriginKind = "library" | "workshop";

/**
 *  Which way an overlay build failed, as the remedy a consumer picks between.
 * 
 *  Mirrors the categories of `ltk_overlay::Error`, which is not `Serialize`,
 *  so records and IPC responses carry this while the detail stays in the
 *  message.
 */
export type OverlayErrorCategory = 
/**  The game installation cannot be used. Point the user at their game dir. */
"GAME_DIR" | 
/**  A mod's content could not be used. Blame the mod, not the game. */
"MOD_CONTENT" | 
/**  The output would exceed a WAD format limit. Splitting a mod helps. */
"WAD_LIMIT" | 
/**  A game file is not what its own metadata says. A repair may help. */
"CORRUPT" | 
/**  An `ltk_overlay` invariant broke. Nothing the user did; report it. */
"BUG" | 
/**  An IO, parse or archive failure with no category of its own. */
"OTHER";

/**  What the DLL said after it attached. */
export type OverlayOutcome = 
/**  `init done`. */
"live" | 
/**  League started before the scan, and the DLL stayed inert. */
"too-late" | 
/**  The DLL refused a game build newer than it knows. */
"end-of-life" | 
/**  The eager scan failed closed on the first bad archive. */
"disabled" | 
/**  A hook did not take. */
"hook-failed" | 
/**  The DLL never attached, or said nothing. */
"none";

/**  Patcher identities */
export type PatcherBinaries = PatcherBinaries_Serialize | PatcherBinaries_Deserialize;

/**  Patcher identities */
export type PatcherBinaries_Deserialize = {
	dll?: BinaryId | null,
	host?: BinaryId | null,
	matchesBundle?: boolean | null,
};

/**  Patcher identities */
export type PatcherBinaries_Serialize = {
	dll?: BinaryId | null,
	host?: BinaryId | null,
	matchesBundle?: boolean | null,
};

/**
 *  Domain errors specific to the patcher.
 * 
 *  Sent over IPC as the `context` payload of an `AppError` with code `PATCHER`.
 *  Frontend code can switch on `kind` to handle each variant.
 */
export type PatcherError = 
/**
 *  Something that mutates the mod library was rejected because a session is
 *  live and pointed at the very files it would rewrite. The caller has to
 *  stop the patcher first - unlike [`Self::AlreadyRunning`], this is not a
 *  stale-status problem.
 */
{ kind: "BUSY" } | 
/**
 *  A start was requested while a session is already live. Benign: it usually
 *  just means the caller's view of the status is stale.
 */
{ kind: "ALREADY_RUNNING" } | 
/**  A stop was requested while nothing was running. */
{ kind: "NOT_RUNNING" } | { kind: "UNSUPPORTED_PLATFORM" } | 
/**
 *  One injection session failed. `stage` separates a host that never came up
 *  from a game that was never patched, since they call for different advice.
 */
{ kind: "INJECTION_FAILED"; stage: InjectionStage; message: string };

/**
 *  The 27 kinds `ltk_meta` reads, as they cross IPC.
 * 
 *  A mirror of [`Kind`], spelled in ritobin's words. The spelling is the tag a row
 *  draws and the word a Problems finding writes. An upstream rename or addition is a
 *  compile error here.
 */
export type PropertyKind = "none" | "bool" | "i8" | "u8" | "i16" | "u16" | "i32" | "u32" | "i64" | "u64" | "f32" | "vec2" | "vec3" | "vec4" | "mtx44" | "rgba" | "string" | "hash" | "file" | "list" | "list2" | "pointer" | "embed" | "link" | "option" | "map" | "flag";

/**  Remote member presence information from the room server. */
export type RemoteMemberInfo = {
	memberId: string,
	role: string,
	lastAcknowledgedRevision: number,
	ackStatus: string,
	isOnline: boolean,
	isStale: boolean,
};

/**  Cache facts suitable for IPC. File paths and room credentials never cross this boundary. */
export type RoomCacheStatus = {
	joinedRooms: number,
	referencedBlobs: number,
	pendingTransfers: number,
};

/**
 *  Durable local workflow facts suitable for the room UI.
 * 
 *  It contains no cache paths, credentials, local-mod mappings, or game state. A profile binding
 *  only identifies the profile the user may choose through the existing profile flow.
 */
export type RoomLocalStatus = {
	preparedRevision: number | null,
	profile: RoomProfileBinding | null,
};

/**  Immutable description of the exact files in one room revision. */
export type RoomManifest = {
	schemaVersion: number,
	roomId: string,
	revision: number,
	/**  Informational compatibility value. Synchronization itself does not inspect the game. */
	gameBuild: string | null,
	/**  Manifest order is the suggested future profile priority order. */
	mods: RoomMod[],
};

/**  One immutable file referenced by a room revision. */
export type RoomMod = {
	contentHash: ContentHash,
	sizeBytes: number,
	format: RoomModFormat,
	/**  Display-only metadata; it is never used as a filesystem path. */
	displayName: string,
	/**  Display-only source version. */
	version: string,
	/**  A suggestion for an explicit future local import action, not an instruction to apply it. */
	suggestedLayers?: string[],
};

/**  Formats accepted as immutable room blobs. */
export type RoomModFormat = "modpkg" | "fantome";

/**
 *  Summary of an explicit local preparation. Local UUIDs remain internal to the library and are
 *  available through its existing APIs; no game-changing action has happened at this point.
 */
export type RoomPreparationSummary = {
	roomId: string,
	revision: number,
	importedCount: number,
	reusedCount: number,
};

export type RoomProfileBinding = {
	roomId: string,
	revision: number,
	localProfileId: string,
	updatedAtMs: number,
};

/**
 *  Result of creating/updating the dedicated room profile. The profile is not selected; the user
 *  must use the existing profile chooser and Start/Play flow themselves.
 */
export type RoomProfileSummary = {
	roomId: string,
	revision: number,
	profileId: string,
};

export type RoomSyncBlockReason = "authorization" | "protocol" | "storage" | "integrity" | "compatibility";

/**  Stable categories for the isolated room synchronization IPC boundary. */
export type RoomSyncErrorKind = "STATE" | "CACHE" | "SYNCHRONIZATION" | "PREPARATION" | "PROFILE" | "INTERRUPTED";

export type RoomSyncPhase = "disconnected" | "connecting" | "comparing" | "transferring" | "verifying" | "synchronized" | "stale" | "blocked";

export type RoomSyncSnapshot = {
	roomId: string,
	phase: RoomSyncPhase,
	/**  Last revision committed transactionally and safe to keep using. */
	activeRevision: number,
	/**  Revision being compared/downloaded, or one announced by the server. */
	targetRevision: number | null,
	totalBlobs: number,
	verifiedBlobs: number,
	missingBlobs: number,
	previousRevisionAvailable: boolean,
	blockReason: RoomSyncBlockReason | null,
};

/**  Where a row sits in the tree. */
export type RowNode = 
/**  An object of the file. */
"object" | 
/**  A property of an object, a struct or an embedded. */
"property" | 
/**  One element of a container, or the value of a present optional. */
"element" | 
/**  One entry of a map. */
"entry";

/**  Which scan the DLL ran, as it decided from the flags and the command line. */
export type ScanMode = "eager" | "lazy";

/**
 *  The status the scan reported, read once for every consumer.
 * 
 *  Carried on the [`Incident`] so a consumer can tell one rejection from
 *  another without reading [`Verdict::cause`] as prose, and sent beside the raw
 *  code on `patcher-wad-scan-failed` so the dialog keeps no second table.
 */
export type ScanStatus = 
/**  An official Riot skin ported onto a base champion. */
"skinhack" | 
/**  A linked `.bin` the archive needs is absent. */
"missing-bin" | 
/**  Unreadable, or built for an unsupported version. */
"corrupt" | 
/**  The game ran out of memory mid-scan. */
"out-of-memory" | 
/**  A skin with a mesh missing, which reads as an incomplete mod. */
"base-skin" | 
/**
 *  The game's own copy of the archive is what the scan objected to.
 * 
 *  No blocking line carries this today, because the DLL keeps a baseline
 *  anomaly out of the phrase the manager greps. Read anyway, so the table
 *  stays whole against the DLL's.
 */
"base-wad" | 
/**  A status this build does not know. */
"unknown";

/**  A session that failed before any game ran. */
export type SessionFailure = 
/**
 *  The overlay build failed, with the builder's own words.
 * 
 *  `kind` is carried because `message` is [`Display`](std::fmt::Display)
 *  output and several [`AppError`](crate::error::AppError) variants render
 *  with no prefix of their own, so a thin inner error leaves nothing at all
 *  to read. The kind is always there to say what failed. `category` is the
 *  overlay's own word on which remedy applies, and `None` on records from
 *  before it was recorded and on failures that never reached the builder.
 */
({ build: {
	kind: ErrorKind,
	category?: OverlayErrorCategory | null,
	message: string,
} }) & { injection?: never } | 
/**  The host did not start, or the DLL did not attach. */
({ injection: {
	stage: InjectionStage,
	message: string,
} }) & { build?: never };

/**  What a patching session was started for, and what it covers. */
export type SessionOrigin = 
/**  The library's enabled mods. */
{ kind: "library" } | 
/**  A workshop test over these project directories. */
{ kind: "workshop"; 
/**  Absolute paths to the project directories under test. */
projects: string[] };

/**
 *  Severity of a diagnostic check result.
 * 
 *  Variants are declared best-to-worst (`Ok < Info < Warn < Bad`). The
 *  frontend re-sorts to display worst-first; do not derive `Ord` from this
 *  declaration order without revisiting the UI sort logic in
 *  `DiagnosticsReport.tsx`.
 */
export type Severity = 
/**  Check passed. */
"ok" | 
/**  Informational - no action needed (e.g. CPU model, language). */
"info" | 
/**  Suspicious - may cause problems, worth investigating. */
"warn" | 
/**  Known to break the patcher, should be fixed. */
"bad";

/**  An archive the lazy scan skipped, with the DLL's reason. */
export type SkippedArchive = {
	wad: string,
	why: string,
};

/**
 *  A verdict as a file holds it, which is every field the kind does not decide.
 * 
 *  [`Verdict`] deserializes through this, so an incident stored before
 *  [`Consequence`] existed reads with the consequence its kind has always
 *  implied, and one stored after it cannot carry a consequence that disagrees.
 */
export type StoredVerdict = StoredVerdict_Serialize | StoredVerdict_Deserialize;

/**
 *  A verdict as a file holds it, which is every field the kind does not decide.
 * 
 *  [`Verdict`] deserializes through this, so an incident stored before
 *  [`Consequence`] existed reads with the consequence its kind has always
 *  implied, and one stored after it cannot carry a consequence that disagrees.
 */
export type StoredVerdict_Deserialize = {
	kind: VerdictKind,
	titleOverride?: string | null,
	cause: string,
	subject: string | null,
	hints?: Hint[],
};

/**
 *  A verdict as a file holds it, which is every field the kind does not decide.
 * 
 *  [`Verdict`] deserializes through this, so an incident stored before
 *  [`Consequence`] existed reads with the consequence its kind has always
 *  implied, and one stored after it cannot carry a consequence that disagrees.
 */
export type StoredVerdict_Serialize = {
	kind: VerdictKind,
	titleOverride: string | null,
	cause: string,
	subject: string | null,
	hints: Hint[],
};

/**  A mod, or a workshop project, that the evidence implicates. */
export type Suspect = {
	modId: string | null,
	projectPath: string | null,
	displayName: string,
	/**
	 *  `writes Aatrox.wad.client, which holds the path`
	 * 
	 *  The reason is the whole claim. How direct the link is reads out of what
	 *  it says - holding the path is not the same sentence as having been
	 *  redirected - so no separate word grades it.
	 */
	because: string,
	/**
	 *  The same claim as a word, for a reader that groups rather than reads.
	 * 
	 *  [`Suspect::because`] names the archives, so it is prose and one of a kind
	 *  per suspect. This is what a count is taken over. Defaulted, because an
	 *  incident stored before it existed carries no reason.
	 */
	reason?: Because,
};

/**
 *  What a frontend crash reports, as the boundary and the two window handlers
 *  hand it over.
 */
export type UiError = {
	/**  The error's constructor name, which is what an issue groups on. */
	name: string,
	message: string,
	/**  The stack as the engine wrote it, unresolved until the maps are uploaded. */
	stack: string | null,
	/**  Which components were mounted, where React gives one. */
	componentStack: string | null,
	/**  The route the reader was on, which is the location a crash carries. */
	route: string | null,
	/**  Whether anything caught it, which the vendor draws on an issue. */
	handled: boolean,
};

/**  What the manager concluded from one game. */
export type Verdict = Verdict_Serialize | Verdict_Deserialize;

/**  Which failure the classifier named. */
export type VerdictKind = 
/**  The DLL never attached, which is the common startup failure. */
"patcher-did-not-run" | 
/**  The overlay could not be built, so there was nothing to inject. */
"overlay-build-failed" | 
/**  The injection host never came up. */
"injection-host-failed" | "patcher-out-of-date" | "archive-rejected" | 
/**
 *  The scan rejected an archive for a Riot skin ported onto a base
 *  champion, which is the rejection a player has a word for.
 */
"skinhack-detected" | "overlay-disabled" | "unmodded" | "missing-data" | "corrupt-archive" | "texture-failed" | "out-of-memory" | "graphics-fault" | "stuck-loading" | "archive-skipped" | "ended-without-reason" | 
/**  The game ran from another install than the overlay was built for. */
"wrong-install";

/**  What the manager concluded from one game. */
export type Verdict_Deserialize = StoredVerdict_Deserialize;

/**  What the manager concluded from one game. */
export type Verdict_Serialize = {
	kind: VerdictKind,
	/**
	 *  The title as it reads, from [`VerdictKind::title`] unless this verdict
	 *  named its own.
	 * 
	 *  Derived on the way in, so a stored incident cannot keep a title this
	 *  build has stopped using. Renaming a kind renames its history with it.
	 */
	title: string,
	/**
	 *  A title for something the kind's own does not cover, and `None` for
	 *  every verdict the predefined set already describes.
	 */
	titleOverride: string | null,
	/**  One or two sentences under the title. */
	cause: string,
	/**  The archive, the path's file name, or the step, where there is one. */
	subject: string | null,
	/**
	 *  What the game lost, which [`VerdictKind`] alone decides.
	 * 
	 *  Written out for a reader, and never read back. [`Self::kind`] decides it,
	 *  so reading it from a file would only let a stale one disagree.
	 */
	consequence: Consequence,
	/**  At most two. */
	hints: Hint[],
};

/**
 *  Domain errors specific to workshop operations.
 * 
 *  Sent over IPC as the `context` payload of an `AppError` with code `WORKSHOP`.
 *  Frontend code can switch on `kind` to handle each variant.
 */
export type WorkshopError = 
/**  One or more files already exist in the target layer directory. */
{ kind: "LAYER_FILE_CONFLICT"; conflicts: string[] };

