// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedAsset } from "./NamedAsset";

/**
 * One clip an animation graph plays out of a single `.anm`.
 */
export type AnimationClip = { 
/**
 * The clip's key as the tables name it, and its hash where none does.
 */
name: string, 
/**
 * The key, `0x` and eight hex digits.
 */
hash: string, 
/**
 * `mAnimationResourceData.mAnimationFilePath`.
 */
animation: NamedAsset, };
