// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";
import type { RoomModFormat } from "./RoomModFormat";

/**
 * Fingerprint of the exact installed archive bytes a publisher offers to a room.
 */
export type CanonicalRoomArtifact = { contentHash: ContentHash, sizeBytes: bigint, format: RoomModFormat, };
