// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SHA-256 rendered as exactly 64 lowercase hexadecimal characters.
 */
export type ContentHash = string;
