// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One effect a skin wears for as long as the character stands.
 */
export type IdleEffect = { 
/**
 * `effectKey`, `0x` and eight hex digits.
 */
effectKey: string, 
/**
 * The system the skin's resolver maps the key to, where this document declares it.
 */
system: string | null, 
/**
 * `boneName`, the joint the effect rides.
 */
bone: string, 
/**
 * `targetBoneName`, the joint it aims at, and empty for one that aims at none.
 */
targetBone: string, 
/**
 * `Position`, the effect's offset from its joint.
 */
position: [number, number, number], };
