// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";

/**
 * A path a bin names, and where its bytes live.
 */
export type NamedAsset = { 
/**
 * The path as the bin spells it, or a chunk's sixteen hex digits where no table
 * names it.
 */
path: string, 
/**
 * Absent for a path nothing on this machine holds, which is not an error.
 */
asset: AssetRef | null, };
