// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";
import type { RoomModFormat } from "./RoomModFormat";
import type { TransferDirection } from "./TransferDirection";
import type { TransferState } from "./TransferState";

export type PendingTransfer = { roomId: string, contentHash: ContentHash, direction: TransferDirection, state: TransferState, format: RoomModFormat, expectedSizeBytes: bigint, transferredBytes: bigint, etag: string | null, updatedAtMs: bigint, };
