// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreparedModMapping } from "./PreparedModMapping";

export type PreparedRevision = { roomId: string, revision: bigint, preparedAtMs: bigint, mappings: Array<PreparedModMapping>, };
