// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a profile's ordering is maintained.
 */
export type ProfileOrderMode = "library" | "roomPinned";
