// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomPresenceState } from "./RoomPresenceState";

/**
 * One presence transition announced to room UI listeners.
 */
export type RoomPresenceChanged = { roomId: string, memberId: string, state: RoomPresenceState, };
