// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";
import type { RoomModFormat } from "./RoomModFormat";

/**
 * One immutable file referenced by a room revision.
 */
export type RoomMod = { contentHash: ContentHash, sizeBytes: bigint, format: RoomModFormat, 
/**
 * Display-only metadata; it is never used as a filesystem path.
 */
displayName: string, 
/**
 * Display-only source version.
 */
version: string, 
/**
 * Whether this room profile enables the mod. Disabled mods remain part of the manifest so
 * every member keeps the same profile state without re-downloading them on re-enable.
 */
enabled: boolean,
/**
 * A suggestion for an explicit future local import action, not an instruction to apply it.
 */
suggestedLayers: Array<string>, };
