// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomPublishStage } from "./RoomPublishStage";

/**
 * Coarse publication progress. Byte-level progress for each mod remains in
 * [`TransferProgress`], while this event covers hashing, manifest commit, and local finalization.
 */
export type RoomPublishProgress = { roomId: string, stage: RoomPublishStage, completedMods: number, totalMods: number, };
