// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A locally observed member-state transition for one synchronized room.
 *
 * The service added later supplies remote presence; the desktop already uses the same event for
 * its own join and leave transitions. Neither variant carries a password, token, endpoint, or
 * filesystem path.
 */
export type RoomPresenceState = "joined" | "left";
