// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Actionable reason for a room error. Unlike lower-level error prose, these values cannot leak
 * local paths, credentials, or signed transfer URLs across the IPC boundary.
 */
export type RoomSyncErrorReason = "SERVER_UNAVAILABLE" | "REQUEST_TIMED_OUT" | "ROOM_NOT_FOUND" | "ROOM_EXPIRED" | "INVALID_PASSWORD" | "RATE_LIMITED" | "ROOM_ALREADY_EXISTS" | "INVALID_ROOM_ID" | "PASSWORD_TOO_SHORT" | "ALREADY_IN_ROOM" | "OPERATION_IN_PROGRESS" | "SESSION_EXPIRED" | "REVISION_CONFLICT" | "STORAGE_QUOTA_EXCEEDED" | "SHARED_FILE_UNAVAILABLE" | "INTEGRITY_CHECK_FAILED" | "INVALID_SERVER_RESPONSE" | "SERVER_ERROR" | "LOCAL_STATE" | "LOCAL_CACHE" | "LOCAL_PREPARATION" | "LOCAL_PROFILE" | "CREDENTIAL_STORE" | "LOCAL_FILE" | "SYNCHRONIZATION" | "INTERRUPTED";
