// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the room worker is doing right now. Unlike transfer progress, this also covers the
 * otherwise invisible periods spent checking the room and rebuilding its local profile.
 */
export type RoomActivityStage = "idle" | "checking" | "preparing" | "uploading" | "publishing" | "downloading" | "updatingProfile" | "complete" | "failed";
