// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomSyncBlockReason } from "./RoomSyncBlockReason";
import type { RoomSyncPhase } from "./RoomSyncPhase";

export type RoomSyncSnapshot = { roomId: string, phase: RoomSyncPhase, 
/**
 * Last revision committed transactionally and safe to keep using.
 */
activeRevision: bigint, 
/**
 * Revision being compared/downloaded, or one announced by the server.
 */
targetRevision: bigint | null, totalBlobs: number, verifiedBlobs: number, missingBlobs: number, previousRevisionAvailable: boolean, blockReason: RoomSyncBlockReason | null, };
