// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Formats accepted as immutable room blobs.
 */
export type RoomModFormat = "modpkg" | "fantome";
