// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomProfileBinding = { roomId: string, revision: bigint, localProfileId: string, updatedAtMs: bigint, };
