// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable categories for the isolated room synchronization IPC boundary.
 */
export type RoomSyncErrorKind = "STATE" | "CACHE" | "SYNCHRONIZATION" | "PREPARATION" | "PROFILE" | "INTERRUPTED";
