// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomMod } from "./RoomMod";

/**
 * Immutable description of the exact files in one room revision.
 */
export type RoomManifest = { schemaVersion: number, roomId: string, revision: bigint, 
/**
 * Informational compatibility value. Synchronization itself does not inspect the game.
 */
gameBuild: string | null, 
/**
 * Manifest order is the suggested future profile priority order.
 */
mods: Array<RoomMod>, };
