// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomActivityStage } from "./RoomActivityStage";

/**
 * Observable room-worker state. Timestamps are Unix milliseconds and let the renderer explain
 * whether a completed/failed status is fresh without receiving paths or transport credentials.
 */
export type RoomActivity = { roomId: string, stage: RoomActivityStage, updatedAtMs: bigint, };
