// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which stage a shared room profile publication has reached.
 */
export type RoomPublishStage = "preparing" | "uploading" | "publishing" | "finalizing" | "complete" | "failed";
