// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdleEffect } from "./IdleEffect";
import type { NamedAsset } from "./NamedAsset";
import type { SubmeshTexture } from "./SubmeshTexture";

/**
 * A skin, as a viewport draws it.
 */
export type SkinModel = { 
/**
 * The `.skn`, `skinMeshProperties.simpleSkin`.
 */
mesh: NamedAsset | null, 
/**
 * The `.skl`, `skinMeshProperties.skeleton`.
 */
skeleton: NamedAsset | null, 
/**
 * The texture a submesh draws with where no override names its own.
 */
texture: NamedAsset | null, 
/**
 * The submeshes a `materialOverride` gives a texture of their own.
 */
overrides: Array<SubmeshTexture>, 
/**
 * The submeshes `initialSubmeshToHide` names, which the character starts without.
 */
hidden: Array<string>, 
/**
 * `skinScale`, which the character is drawn at.
 */
scale: number, 
/**
 * `skinAnimationProperties.animationGraphData`, `0x` and eight hex digits.
 */
animationGraph: string | null, 
/**
 * `idleParticlesEffects`, in the order the skin lists them.
 */
idleEffects: Array<IdleEffect>, };
