// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";
import type { TransferDirection } from "./TransferDirection";

export type TransferProgress = { roomId: string, contentHash: ContentHash, direction: TransferDirection, transferredBytes: bigint, totalBytes: bigint, attempt: number, };
