// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VfxValue } from "./VfxValue";

/**
 * One property of a resolved struct.
 */
export type VfxField = { 
/**
 * `0x` and eight hex digits.
 */
hash: string, 
/**
 * The property as the tables name it. Absent where no table does.
 */
name: string | null, 
/**
 * What the property holds, resolved.
 */
value: VfxValue, };
