// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VfxValue } from "./VfxValue";

/**
 * One entry of a resolved map.
 */
export type VfxMapEntry = { 
/**
 * A named hash key by its name, an unnamed one as hex, and every other kind as the
 * wire form writes it.
 */
key: string, 
/**
 * What the entry holds, resolved.
 */
value: VfxValue, };
