// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The object a resolved struct holds the properties of, where a walk reached one.
 */
export type VfxObject = { 
/**
 * The object's path hash, `0x` and eight hex digits.
 */
entry: string, 
/**
 * The object's path. Absent where no table names it.
 */
name: string | null, };
