// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VfxValue } from "./VfxValue";

/**
 * One particle system, as the renderer reads it.
 */
export type VfxSystem = { 
/**
 * The object's path hash, `0x` and eight hex digits.
 */
entry: string, 
/**
 * The object's path. Absent where no table names it.
 */
name: string | null, 
/**
 * `0x` and eight hex digits.
 */
classHash: string, 
/**
 * The class as the tables name it. Absent where no table does.
 */
class: string | null, 
/**
 * The object's own properties, resolved. Always a [`VfxValue::Struct`].
 */
root: VfxValue, };
