// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";
import type { VfxField } from "./VfxField";
import type { VfxMapEntry } from "./VfxMapEntry";
import type { VfxObject } from "./VfxObject";

/**
 * A value of a resolved system's tree.
 */
export type VfxValue = { "type": "bool", value: boolean, } | { "type": "number", value: number, } | { "type": "vector", values: Array<number>, } | { "type": "matrix", values: Array<number>, } | { "type": "string", value: string, } | { "type": "hash", hash: string, name: string | null, } | { "type": "asset", path: string, asset: AssetRef | null, } | { "type": "link", hash: string, name: string | null, } | { "type": "struct", classHash: string, class: string | null, fields: Array<VfxField>, 
/**
 * The object whose properties these are, absent for an embedded struct.
 */
object: VfxObject | null, } | { "type": "container", items: Array<VfxValue>, } | { "type": "map", entries: Array<VfxMapEntry>, } | { "type": "null" } | { "type": "none" } | { "type": "undrawn" };
